name:                Bali
version:             0.1.0.0
github:              "Gompilers/Bali"
license:             GPLv3
author:              "Gompiler Team"
maintainer:          "me@allanwang.ca"
copyright:           "2018 Gompiler Team"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gompiler/Bali#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- parser-combinators
- primitive
- hspec
- text
- neat-interpolation
- bytestring
- filepath
- file-embed

library:
  source-dirs: src

executables:
  Bali-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Bali

tests:
  Bali-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Bali
